version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: life-pharmacy-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - life-pharmacy

  nginx:
    image: nginx:alpine
    container_name: life-pharmacy-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - life-pharmacy

  db:
    image: mysql:8.0
    container_name: life-pharmacy-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - life-pharmacy

  redis:
    image: redis:alpine
    container_name: life-pharmacy-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - life-pharmacy

networks:
  life-pharmacy:
    driver: bridge

volumes:
  dbdata: 